events {}

http {
    server {
        listen 80;

        # Front — React uygulaması
        location / {
            proxy_pass http://dashboard-ui:80;
        }

        # API ve Auth istekleri — Gateway'e
        location /api/ {
            proxy_pass http://gateway:9000;
        }

        location /auth/ {
            proxy_pass http://gateway:9000;
        }

        # MQTT WebSocket — direkt EMQX'e
        location /mqtt {
            proxy_pass http://emqx:8083;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
